name: Deploy PRD
on:
  workflow_call:
    inputs:
      dockerfile_location:
        required: false
        type: string
        default: "."
      templates_location:
        required: false
        type: string
        default: "deployment/"
      environment:
        default: "Production"
        required: false
        type: string
      cluster_namespace:
        default: "easetrack"
        required: false
        type: string
      environment_url:
        required: true
        type: string
      release:
        default: "false"
        required: false
        type: string
      envfile_to_env:
        default: "false"
        required: false
        type: string
      namespace:
        default: "prd"
        required: false
        type: string
      app_location:
        default: "app/"
        required: false
        type: string
      platforms:
        default: "linux/amd64"
        required: false
        type: string
    secrets:
      AWS_DEVOPS_ROLE_NAME:
        required: true
      AWS_DEVOPS_REGION:
        required: true
      AWS_DEVOPS_ECR:
        required: true
      AWS_PRD_CLUSTER_NAME:
        required: true
      AWS_PRD_ROLE_NAME:
        required: true
      AWS_PRD_REGION:
        required: true
      GH_PAT:
        required: true
jobs:
  Deploying:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      actions: write
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.environment_url }}
    steps:
      - name: Configura as credenciais da AWS (Dev)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: ${{ secrets.AWS_PRD_REGION }}
          role-to-assume: ${{ secrets.AWS_PRD_ROLE_NAME }}

      - name: Instala e configura o kubeclt
        run: |
          aws eks update-kubeconfig --name ${{ secrets.AWS_PRD_CLUSTER_NAME }} --region ${{ secrets.AWS_PRD_REGION }}

      - name: Checkout do repositório
        uses: actions/checkout@master

      - name: Verifica a tag para upload no ECR
        id: ecr-pretag
        if: ${{ inputs.environment != 'Production' }}
        run: echo "ecr_pretag=${{ inputs.namespace }}-" >> $GITHUB_OUTPUT

      - name: Recupera o histórico da versão para a criação da release
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_depth: 10
          version: ${{ steps.vars.outputs.project_version }}
          path: ./CHANGELOG.md

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Atribui variáveis de ambiente para realizar os uploads
        id: vars
        run: |
          echo "branch_name=${{ steps.extract_branch.outputs.branch }}" >> $GITHUB_OUTPUT
          echo "project_version=$(cat .version)" >> $GITHUB_OUTPUT
          echo "sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          echo "repo_name=${GITHUB_REPOSITORY#*\/}" >> $GITHUB_OUTPUT
          echo "ecr_registry=${{ secrets.AWS_DEVOPS_ECR }}" >> $GITHUB_OUTPUT
          echo "ecr_tag=${{ secrets.AWS_DEVOPS_ECR }}/${GITHUB_REPOSITORY#*\/}:${{ steps.ecr-pretag.outputs.ecr_pretag }}${GITHUB_SHA}" >> $GITHUB_OUTPUT
          echo "ecr_tag_latest=${{ secrets.AWS_DEVOPS_ECR }}/${GITHUB_REPOSITORY#*\/}:${{ steps.ecr-pretag.outputs.ecr_pretag }}latest" >> $GITHUB_OUTPUT
          echo "ecr_tag_latest_escaped=${{ secrets.AWS_DEVOPS_ECR }}\/${GITHUB_REPOSITORY#*\/}:${{ steps.ecr-pretag.outputs.ecr_pretag }}${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Add building label to Deployment
        run: |
          kubectl label deployment ${{ steps.vars.outputs.repo_name }} \
            build-status=building --overwrite -n ${{ inputs.cluster_namespace }}

      - name: Configura o arquivo .env estático de acordo com o ambiente
        if: ${{ inputs.envfile_to_env != 'false' }}
        run: |
          mv ${{ inputs.envfile_to_env }} ${{ inputs.app_location }}.env
          rm ${{ inputs.app_location }}.env.*

      - name: Instala o Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Configura as credenciais da AWS (DevOps)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: ${{ secrets.AWS_DEVOPS_REGION }}
          role-to-assume: ${{ secrets.AWS_DEVOPS_ROLE_NAME }}

      - name: Autentica com o AWS ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Constrói a imagem e faz upload para o AWS ECR
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.dockerfile_location }}
          push: true
          tags: "${{ steps.vars.outputs.ecr_tag_latest }},${{ steps.vars.outputs.ecr_tag }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: ${{ inputs.platforms }}
          build-args: |
            "GH_PAT=${{ secrets.GH_PAT }}"
            "BRANCH_NAME=${{ steps.vars.outputs.branch_name }}"
            "ENVIRONMENT=production"

      - name: Configura as credenciais da AWS (Dev)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: ${{ secrets.AWS_PRD_REGION }}
          role-to-assume: ${{ secrets.AWS_PRD_ROLE_NAME }}

      - name: Instala e configura o kubeclt
        run: |
          aws eks update-kubeconfig --name ${{ secrets.AWS_PRD_CLUSTER_NAME }} --region ${{ secrets.AWS_PRD_REGION }}

      - name: Checkout do repositório de templates
        uses: actions/checkout@master
        with:
          repository: ${{ vars.EKS_TEMPLATES_REPO }}
          path: "target"
          token: ${{ secrets.GH_PAT }}

      - name: Aplica o template no K8S
        run: |
          TEMPLATE=target/services/${{ steps.vars.outputs.repo_name }}/template.yml
          APP_ENV_FILE=target/services/${{ steps.vars.outputs.repo_name }}/envs.sh
          CURRENT_DIR=$(dirname -- "$0")
          ENV_FILE="target/envs/${{ inputs.namespace }}-pipeline.sh"
          export BRANCH_NAME="${{ steps.vars.outputs.branch_name }}"
          export PROJECT_VERSION="${{ steps.vars.outputs.project_version }}"
          source "${ENV_FILE}"
          source "${APP_ENV_FILE}"
          envsubst < $TEMPLATE > template_result.yml
          sed -i '/^\([[:space:]]*image: *\).*/s//\1${{ steps.vars.outputs.ecr_tag_latest_escaped }}/;' template_result.yml
          kubectl apply -f template_result.yml --validate=false

      - name: Update build label to Deployment
        run: |
          kubectl label deployment ${{ steps.vars.outputs.repo_name }} build-status=done --overwrite -n ${{ inputs.cluster_namespace }}

      - name: Cria a release no Github para a versão
        if: ${{ inputs.release == 'true' }}
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.vars.outputs.project_version }}
          name: v${{ steps.vars.outputs.project_version }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          prerelease: ${{ steps.changelog_reader.outputs.status == 'prereleased' }}
          draft: ${{ steps.changelog_reader.outputs.status == 'unreleased' }}
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Purge old cache
        uses: MyAlbum/purge-cache@v2
        with:
          debug: true
          max-age: 604800

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
